version: '3.1'

services:
  db:
    container_name: "constructor-web-db"
    image: postgres:14.1-alpine
    env_file:
      - ".env"
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#  test-db:
#    container_name: "test-constructor-web-db"
#    image: postgres:14.1-alpine
#    env_file:
#      - ".env"
#    restart: always
#    volumes:
#      - ./postgresql:/var/lib/postgresql/data
#    ports:
#      - "5433:5432"